Fix compilation for 32-bit systems (#717)
* Fix compilation for 32-bit systems

Include HandleLLVMOptions to ensure LLVM and clspv components are
compiled using the same defines (for example -D_FILE_OFFSET_BITS=64
-D_LARGEFILE_SOURCE). This essentially fixes this undefined reference to
    clang::FileManager::getVirtualFile(llvm::StringRef, long, long)
while the following was actually defined
    clang::FileManager::getVirtualFile(llvm::StringRef, long long, long)
.

As a consequence, the compilation and link options are updated and
require fixes to the dependency lists of clspv_passes and clspv_core.

Signed-off-by: Marco Antognini <marco.antognini@arm.com>

* Address warnings

With the previous update, additional warnings are generated by default.
This patch addresses these:

 * -Wunused-function: use `inline` instead of `static` in header.
 * -Wunused-but-set-variable: code is protected in #ifndef NDEBUG when
   it is only used for the purpose of assertions.
 * -Wunused-function and -Wunused-but-set-variable: dead code is
   removed.
 * -Wsign-compare: uses of `auto` are replaced with `unsigned` or
   `size_t`, or use `static_cast`.
 * -Wimplicit-fallthrough: this warning is silenced using special
   comments.
 * -Wpedantic: remove extra `;` on closing brace for namespace.
 * -Woverflow: use types explicitly sized (e.g. std::uint64_t) and
   appropriate macros for minimum-width integer constants instead of
   size_t.

Signed-off-by: Marco Antognini <marco.antognini@arm.com>