Address linking issues with shared build
Link against LLVMCodeGen to solve the follow issues when doing a
shared-library build:

    lib/libclspv_core.so: undefined reference to `llvm::createHardwareLoopsPass()'
    lib/libclspv_core.so: undefined reference to `llvm::createCodeGenPreparePass()'
    lib/libclspv_core.so: undefined reference to `llvm::createExpandMemCmpPass()'
    lib/libclspv_core.so: undefined reference to `llvm::createSafeStackPass()'

The issue was introduce with b41cfd36 (Update LLVM (#711), 2021-02-17).

Signed-off-by: Marco Antognini <marco.antognini@arm.com>