Fix compilation for 32-bit systems
Include HandleLLVMOptions to ensure LLVM and clspv components are
compiled using the same defines (for example -D_FILE_OFFSET_BITS=64
-D_LARGEFILE_SOURCE). This essentially fixes this undefined reference to
    clang::FileManager::getVirtualFile(llvm::StringRef, long, long)
while the following was actually defined
    clang::FileManager::getVirtualFile(llvm::StringRef, long long, long)
.

As a consequence, the compilation and link options are updated and
require fixes to the dependency lists of clspv_passes and clspv_core.

Signed-off-by: Marco Antognini <marco.antognini@arm.com>