Fix missing link reference to build clspv-opt
Link against LLVMSupport to fix this issue:

    clspv-opt.dir/main.cpp.o: undefined reference to symbol '_ZTVN4llvm2cl11OptionValueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE'
    libLLVMSupport.so.11git: error adding symbols: DSO missing from command line

This only affects shared library builds.

Add transitive dependencies as well to ensure check-spirv works out of
the box with shared library build.

Signed-off-by: Marco Antognini <marco.antognini@arm.com>